### ISSUE TITLE
Some filetypes are having some issue with treesitter.

### ISSUE THREAD

**Issue by charliie-dev** [s1n7ax/nvim-comment-frame#10]
Filetype `sh` are not recongnized by treesitter. 

Error:
![image](https://user-images.githubusercontent.com/32497323/194827201-a4802baa-8109-4f3a-9025-fee5f81541a6.png)

It could be fixed by manually execute `:set filetype=bash` when editting in a `sh` filetype buffer, and the plugin will work.

A more elaborate list of what I had tried to fix this issue, please refer to https://github.com/ayamir/nvimdots/discussions/272.

**Comment by charliie-dev** [comment]
My configs:


<details><summary>treesitter.lua</summary>
<p>

```lua
vim.api.nvim_set_option_value("foldmethod", "expr", {})
vim.api.nvim_set_option_value("foldexpr", "nvim_treesitter#foldexpr()", {})

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"css",
		"go",
		"gomod",
		"html",
		"javascript",
		"json",
		"latex",
		"lua",
		"make",
		"python",
		"rust",
		"toml",
		"tsx",
		"typescript",
		"typescript",
		"vim",
		"yaml",
	},
	sync_install = true,
	ignore_install = { "markdown" },
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = ",s",
			node_incremental = ",s",
			scope_incremental = ",n",
			node_decremental = ",n",
		},
	},
	highlight = {
		enable = true,
		disable = { "help", "markdown" },
		additional_vim_regex_highlighting = true,
	},
	textobjects = {
		select = {
			enable = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@class.outer",
				["ic"] = "@class.inner",
			},
		},
		move = {
			enable = true,
			set_jumps = true, -- whether to set jumps in the jumplist
			goto_next_start = {
				["]["] = "@function.outer",
				["]m"] = "@class.outer",
			},
			goto_next_end = {
				["]]"] = "@function.outer",
				["]M"] = "@class.outer",
			},
			goto_previous_start = {
				["[["] = "@function.outer",
				["[m"] = "@class.outer",
			},
			goto_previous_end = {
				["[]"] = "@function.outer",
				["[M"] = "@class.outer",
			},
		},
	},
	rainbow = {
		enable = true,
		extended_mode = true, -- Highlight also non-parentheses delimiters, boolean or table: lang -> boolean
		max_file_lines = 1000, -- Do not enable for files with more than 1000 lines, int
	},
	context_commentstring = {
		enable = true,
		enable_autocmd = false,
		config = {
			sh = "# %s",
		},
	},
	matchup = { enable = true },
})

require("nvim-treesitter.install").prefer_git = true
local parsers = require("nvim-treesitter.parsers").get_parser_configs()
for _, p in pairs(parsers) do
	p.install_info.url = p.install_info.url:gsub("https://github.com/", "git@github.com:")
end

local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.bash.filetype_to_parsername = { "sh" }
```

</p>
</details>

<details><summary>comment-frame.lua</summary>
<p>

```lua
require("nvim-comment-frame").setup({
	-- width of the comment frame
	frame_width = 70,

	-- wrap the line after 'n' characters
	line_wrap_len = 50,

	-- automatically indent the comment frame based on the line
	auto_indent = true,

	-- add comment above the current line
	add_comment_above = true,

	languages = {
		-- configuration for Lua programming language
		-- @NOTE global configuration will be overridden by language level
		-- configuration if provided
		lua = {
			start_str = "--",
			end_str = "--",
			fill_char = "-",
		},
		bash = {
			start_str = "#",
			end_str = "#",
			fill_char = "#",
		},
		sh = {
			start_str = "#",
			end_str = "#",
			fill_char = "#",
		},
		python = {
			start_str = "#",
			end_str = "#",
			fill_char = "#",
		},
	},
})
```

</p>
</details>

**Comment by charliie-dev** [comment]
Probably related to this? https://github.com/s1n7ax/nvim-comment-frame/blob/05be8b4cf2138d341ed5135dc704d9fccf51a3cb/lua/nvim-comment-frame/init.lua#L48-L50

**Comment by charliie-dev** [comment]
After some digging, I checked something:

The default nvim-treesitter's buildin `filetype_to_parsername`
```lua
local ft_to_parsername = require("nvim-treesitter.parsers").filetype_to_parsername
print(vim.inspect(ft_to_parsername))
```

And it turns out `sh` is actucally pass to `bash` parser by default.
![image](https://user-images.githubusercontent.com/32497323/194863694-98a680b9-b894-42de-8af2-df646b2874f8.png)

The default `bash` parser:
![image](https://user-images.githubusercontent.com/32497323/194876528-9ffceffc-5216-49ab-a0bc-d9b0f5bd951a.png)

Nothing goes wrong **at startup** with default `bash` parser when I open a filetype `sh` file, such as `~/.bashrc`, just this plugin won't work and give the error in the first comment.

But when I change filetype "sh" to "bash" via ftdetect, autocommands or add ft hint at the bottom of the file, some error shows up **at startup**. Now the filetype is set to `bash`, but the plugin still won't work.

The error:
![image](https://user-images.githubusercontent.com/32497323/194881675-3e440cf6-4952-447b-b950-4d9d7e6745d9.png)

The **ONLY** promising way for this plugin to work with bash scripts is to execute `:set filetype=bash` or `:setf bash` manually in each bash script buffer, which is kinda annoying but at least it works.

**Comment by s1n7ax** [comment]
This is cased due to the way Neovim treesitter module search for the parser. It's using the current filetype (`sh`) as the language while the registered parser for the buffer is `bash`.

I assume this is Neovim implementation trying to be generic and not necessarily a bug.

Switching to `nvim-treesitter.parsers.get_parser()` function to fix the issue.

![image](https://user-images.githubusercontent.com/18459807/194994367-49691e90-768d-416a-9a43-7c856bf67666.png)

**Comment by s1n7ax** [comment]
@CharlesChiuGit Can you try to change the branch and see, if everything work as expected?

```lua
use { 
    's1n7ax/nvim-comment-frame',
    requires = {
        { 'nvim-treesitter' }
    },
    branch = 'bug/10'
    config = function()
    end
}
```

**Comment by charliie-dev** [comment]
@s1n7ax Thank you for your quick fix! Now the plugin is working as expected with bash scripts. I have been writing quite a bit of bash srcipt these days, it's really nice to have this feature. Thanks again!

P.S. For people who lazy-loading `nvim-treesitter`, don't forget to add the **module** section to it.

For example:

```lua
use {
        "nvim-treesitter/nvim-treesitter",
	opt = true,
	run = ":TSUpdate",
	event = "BufReadPost",
	after = "nvim-treesitter",
	module = {
		"nvim-treesitter",
		"nvim-treesitter.parsers",
	},
	config = function()
	end,
}
```

**Comment by charliie-dev** [comment]
Will the branch `bug/10` got merged?

**Comment by s1n7ax** [comment]
@CharlesChiuGit It is already merged.

**Comment by charliie-dev** [comment]
Nice! Didn't notice that. Sorry!
