### ISSUE TITLE
Manually wrap line after detecting a special character

### ISSUE THREAD

**Issue by phgz** [s1n7ax/nvim-comment-frame#3]
Wonderful project. The line wrap is really what was missing from other similar plugins.

It would be nice if we could also manually cut lines at a desired length instead of solely relying on line wrap after X characters. For example, the string

`Hi, this is indeed a very long string in which i will put a\nnewline char. It is obviously more than 80 characters!`

will render like this:

```
#------------------------------------------------------------------------------#
#  Hi, this is indeed a very long string in which i will put a\nnewline char.  #
#                   It is obviously more than 80 characters!                   #
#------------------------------------------------------------------------------#
```
But it could add a newline when it detects a `\n`, so it would render like that:

```
#------------------------------------------------------------------------------#
#          Hi, this is indeed a very long string in which i will put a         #
#            newline char. It is obviously more than 80 characters!            #
#------------------------------------------------------------------------------#

```

**Comment by s1n7ax** [comment]
I actually handled new lines but apparently `\n` is really a `\\n`. I'm working on it.

**Comment by s1n7ax** [comment]
`<leader>cf` - Single line comment
`<leader>cm` - Multiline comment

More information in the read me. You still can use \n in single line comment to add a new line
