### ISSUE TITLE
Calling line comment above comment , with out indentation ,causes error

### ISSUE THREAD

**Issue by LamprosPitsillos** [s1n7ax/nvim-comment-frame#5]
https://user-images.githubusercontent.com/61395246/132909464-63cb0a14-5d57-4605-8808-a0ad4089de21.mp4

`E5108: Error executing lua ...start/nvim-comment-frame/lua/nvim-comment-frame/util.lua:105: [nvim-comment-frame]: configuration not found for language: comment  `

**Comment by s1n7ax** [comment]
This is due to an issue in language_for_range() API in treesitter. It considers the empty line as a comment line. Now comment frame refer the language trees and their ranges to figure out the language instead.
