### ISSUE TITLE
[Typo ?] `tree:childret()` call causes a nil value error

### ISSUE THREAD

**Issue by JoelTari** [s1n7ax/nvim-comment-frame#6]
https://github.com/s1n7ax/nvim-comment-frame/blob/05be8b4cf2138d341ed5135dc704d9fccf51a3cb/lua/nvim-comment-frame/util.lua#L252

This causes a nil value error when I attempt to add a frame in my init.lua config, although I have not seen this line get called elsewhere.
`tree:children()` instead of `tree:childret()` seems to fix it.

**Comment by s1n7ax** [comment]
Good catch. I made the change. Try updating. [9284b7b](https://github.com/s1n7ax/nvim-comment-frame/commit/9284b7bef194d8522beb504292d61b2fc8d89238)
