### ISSUE TITLE
setup function not executed?

### ISSUE THREAD

**Issue by mengano-net** [s1n7ax/nvim-comment-frame#8]
Great plugin!
I'm having a problem, I'd appreciate your direction troubleshooting it. 

I'm trying to override your plugin's maps by first disabling built-in map. I'm using [Packer](https://github.com/wbthomason/packer.nvim) to manage plugins so I'm trying this:
```
  use {
    's1n7ax/nvim-comment-frame',
    requires = {
      { 'nvim-treesitter' }
    },
    config = function() require('nvim-comment-frame').setup({
        disable_default_keymap = true,
      })
    end,
  }

```

... Yet, I still see the [default map](https://imgur.com/a/TidIAlA) ... what I'm doing wrong? Configuration via setup() function seems simple ... please help and thanks again.

Some other data:
- OS: macos
- nvim:
```
:version
NVIM v0.8.0-dev-1117-g7bd4c8e8e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE
=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99
-Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-
protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DM
IN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.d
eps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Librar
y/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1663565577584.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by mengano-net** [comment]
Screenshot was taken before change … I actually set
`disable_default_keymap = true, `

**Comment by mengano-net** [comment]
Troubleshooting, I found that if I move configuration to its own file, setup function **does** get executed, thus I no longer have the default map ...
```
  use {
    's1n7ax/nvim-comment-frame',
    requires = { 'nvim-treesitter' },
    config = "require('nvim-comment-frame-config')"
  }
```

... then on file `lua/nvim-comment-frame-config/init.lua` we have:
```
❯ cat lua/nvim-comment-frame-config/init.lua
require('nvim-comment-frame').setup({
  disable_default_keymap = true,
})

~/.config/nvim on develop !1 ?1                                                                                                            
❯ 
```

**Comment by s1n7ax** [comment]
@mengano-net I'm pretty sure it's working as expected. When you add something to packer startup, you should run `:PackerCompile` to changes to be applied.

**Comment by mengano-net** [comment]
> @mengano-net I'm pretty sure it's working as expected. When you add something to packer startup, you should run `:PackerCompile` to changes to be applied.

Yes, I am running `:PackerCompile`, my issue was that packer was quitting at a point above nvim-comment-frame section. I'm closing this issue.
Thanks for the attention.
