### ISSUE TITLE
start_str not properly set on lines starting and ending comment block ... observed in python and lua

### ISSUE THREAD

**Issue by mengano-net** [s1n7ax/nvim-comment-frame#9]
- Running Neovim 0.8.0 nightly build, LSP
- my `nvim-comment-frame` config:
```
comment_frame.setup({
  disable_default_keymap = true,
  frame_width = 90,
  line_wrap_len = 79,
  languages = {
    python = {
      frame_width = 61,
      line_wrap_len = 52,
      start_str = '# test #',
    },
    lua = {
      start_str = '---test #'
    }
  }
})
```
- `start_str` only seems to be applied to lines in the block, having actual comments, lines starting and ending comment block do not get value on `start_str`
- On python: `start_str` is not properlly implemented, causing [this linting warning](https://imgur.com/a/D6uH6yA) as comment line should start with `#<space>`
- In Lua, we get something similar: config above generates this comment block:
```
---test-#---------------------------------------------------------------------------------
---test #                         This is a test comment block                          --
---test-#---------------------------------------------------------------------------------
```

**Comment by s1n7ax** [comment]
I'm filling all the empty lines with the fill_char in the top and the bottom lines

https://github.com/s1n7ax/nvim-comment-frame/commit/1c6379300d7ce306657481c4b7a51d72f387ae89 should fix this. Try updating the plugin now

**Comment by s1n7ax** [comment]
Closing the issue. Please reopen if you still facing the issue
